// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEVx83lM9Rtxpn8KK918UIiAwp5vY4cbc',
    appId: '1:606500371452:web:e9b08f855f52891eca1079',
    messagingSenderId: '606500371452',
    projectId: 'fir-flutter-codelabs-4fd41',
    authDomain: 'fir-flutter-codelabs-4fd41.firebaseapp.com',
    storageBucket: 'fir-flutter-codelabs-4fd41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcfVSqTL8vJHlWitE1vpyvchHI93mA-1A',
    appId: '1:606500371452:android:190a8f256be1691eca1079',
    messagingSenderId: '606500371452',
    projectId: 'fir-flutter-codelabs-4fd41',
    storageBucket: 'fir-flutter-codelabs-4fd41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYArSTdpbuyyphFsITsXTJmcADSY3ntk',
    appId: '1:606500371452:ios:e4b930125d1ff722ca1079',
    messagingSenderId: '606500371452',
    projectId: 'fir-flutter-codelabs-4fd41',
    storageBucket: 'fir-flutter-codelabs-4fd41.appspot.com',
    iosClientId: '606500371452-s9ufpn0td5bmovrcmdr69lqbsajf9rsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYArSTdpbuyyphFsITsXTJmcADSY3ntk',
    appId: '1:606500371452:ios:e4b930125d1ff722ca1079',
    messagingSenderId: '606500371452',
    projectId: 'fir-flutter-codelabs-4fd41',
    storageBucket: 'fir-flutter-codelabs-4fd41.appspot.com',
    iosClientId: '606500371452-s9ufpn0td5bmovrcmdr69lqbsajf9rsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
